export interface IpcResponse<T> {
  success: boolean
  data?: T
  error?: string
  code?: string
}

export interface SessionData {
  userId: number
  username: string
  fullName: string
  role: string
  permissions: string[]
}

declare global {
  interface Window {
    electronAPI: {
      auth: { login: (c: { username: string; password: string }) => Promise<IpcResponse<SessionData>>; logout: () => Promise<IpcResponse<null>>; getSession: () => Promise<IpcResponse<SessionData | null>>; changePassword: (d: unknown) => Promise<IpcResponse<null>> }
      settings: { getAll: () => Promise<IpcResponse<Record<string, string>>>; get: (k: string) => Promise<IpcResponse<string | null>>; set: (k: string, v: string) => Promise<IpcResponse<null>>; setBulk: (e: Record<string, string>) => Promise<IpcResponse<null>> }
      products: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; search: (q: string) => Promise<IpcResponse<unknown[]>>; findByBarcode: (b: string) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; adjustStock: (id: number, adj: unknown) => Promise<IpcResponse<null>>; getLowStock: () => Promise<IpcResponse<unknown[]>> }
      categories: { list: () => Promise<IpcResponse<unknown[]>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      brands: { list: () => Promise<IpcResponse<unknown[]>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      suppliers: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      partners: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      customers: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; search: (q: string) => Promise<IpcResponse<unknown[]>> }
      sales: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; void: (id: number, r: string) => Promise<IpcResponse<null>>; addPayment: (saleId: number, d: unknown) => Promise<IpcResponse<null>>; saveDraft: (d: unknown) => Promise<IpcResponse<unknown>>; getDrafts: () => Promise<IpcResponse<unknown[]>>; getDraftById: (id: number) => Promise<IpcResponse<unknown>>; deleteDraft: (id: number) => Promise<IpcResponse<null>> }
      payments: { addPayment: (saleId: number, d: unknown) => Promise<IpcResponse<null>>; getForSale: (saleId: number) => Promise<IpcResponse<unknown[]>> }
      invoices: { getForSale: (saleId: number) => Promise<IpcResponse<unknown>>; generatePdf: (id: number) => Promise<IpcResponse<string>>; print: (id: number) => Promise<IpcResponse<null>>; openPdf: (id: number) => Promise<IpcResponse<null>> }
      repairs: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getByStatus: () => Promise<IpcResponse<unknown[]>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; updateStatus: (id: number, s: string, n?: string) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      reports: { salesDaily: (d: string) => Promise<IpcResponse<unknown>>; salesMonthly: (y: number, m: number) => Promise<IpcResponse<unknown>>; profit: (from: string, to: string) => Promise<IpcResponse<unknown>>; topProducts: (from: string, to: string) => Promise<IpcResponse<unknown[]>>; inventory: () => Promise<IpcResponse<unknown[]>>; lowStock: () => Promise<IpcResponse<unknown[]>>; customerDebts: () => Promise<IpcResponse<unknown[]>>; exportCsv: (t: string, p: unknown) => Promise<IpcResponse<string>> }
      dashboard: { getSummary: () => Promise<IpcResponse<unknown>> }
      users: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; resetPassword: (id: number, pwd: string) => Promise<IpcResponse<null>>; setPermissions: (id: number, p: string[]) => Promise<IpcResponse<null>>; getAllPermissions: () => Promise<IpcResponse<unknown[]>>; getUserPermissions: (id: number) => Promise<IpcResponse<unknown[]>>; getRoleDefaults: (role: string) => Promise<IpcResponse<string[]>>; getUserOverrides: (id: number) => Promise<IpcResponse<unknown[]>>; setOverride: (id: number, k: string, g: boolean) => Promise<IpcResponse<null>>; removeOverride: (id: number, k: string) => Promise<IpcResponse<null>> }
      backup: { create: () => Promise<IpcResponse<unknown>>; restore: (path: string) => Promise<IpcResponse<unknown>>; selectFile: () => Promise<IpcResponse<string | null>>; getSettings: () => Promise<IpcResponse<unknown>>; updateSettings: (d: unknown) => Promise<IpcResponse<null>>; runNow: () => Promise<IpcResponse<unknown>>; chooseFolder: () => Promise<IpcResponse<string | null>>; openFolder: (path: string) => Promise<IpcResponse<null>> }
      license: { check: () => Promise<IpcResponse<unknown>>; activate: (k: string) => Promise<IpcResponse<unknown>>; getStatus: () => Promise<IpcResponse<unknown>>; getHwId: () => Promise<IpcResponse<string>>; getInfo: () => Promise<IpcResponse<unknown>>; hasFeature: (f: string) => Promise<IpcResponse<boolean>>; getTier: () => Promise<IpcResponse<string>>; canAddUser: () => Promise<IpcResponse<boolean>> }
      app: { licenseActivated: () => void }
      activity: { list: (f?: unknown) => Promise<IpcResponse<{ rows: unknown[]; total: number }>> }
      expenseCategories: { list: () => Promise<IpcResponse<unknown[]>>; create: (d: unknown) => Promise<IpcResponse<{ id: number }>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>> }
      expenses: { list: (f?: unknown) => Promise<IpcResponse<{ rows: unknown[]; total: number }>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<{ id: number }>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; selectReceipt: () => Promise<IpcResponse<string | null>>; openReceipt: (path: string) => Promise<IpcResponse<null>>; sumByCategory: (from: string, to: string) => Promise<IpcResponse<unknown[]>>; sumByMonth: (year: number) => Promise<IpcResponse<unknown[]>> }
      vehicles: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; getByOwner: (ownerId: number) => Promise<IpcResponse<unknown[]>> }
      jobCards: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getByStatus: () => Promise<IpcResponse<unknown[]>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; updateStatus: (id: number, s: string) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; addPart: (jobId: number, p: unknown) => Promise<IpcResponse<null>>; removePart: (partId: number) => Promise<IpcResponse<null>>; getForVehicle: (vehicleId: number) => Promise<IpcResponse<unknown[]>> }
      services: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; getCategories: () => Promise<IpcResponse<unknown[]>> }
      jobTypes: { listAll: () => Promise<IpcResponse<unknown[]>>; listActive: () => Promise<IpcResponse<unknown[]>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; reorder: (id: number, dir: 'up' | 'down') => Promise<IpcResponse<null>> }
      customReceipts: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; delete: (id: number) => Promise<IpcResponse<null>> }
      employees: { list: (f?: unknown) => Promise<IpcResponse<unknown[]>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<unknown>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; listVacations: (empId: number) => Promise<IpcResponse<unknown[]>>; addVacation: (d: unknown) => Promise<IpcResponse<null>>; endVacation: (vacId: number, date: string) => Promise<IpcResponse<null>>; deleteVacation: (vacId: number) => Promise<IpcResponse<null>>; listDocuments: (empId: number) => Promise<IpcResponse<unknown[]>>; uploadDocument: (d: unknown) => Promise<IpcResponse<unknown>>; openDocument: (docId: number) => Promise<IpcResponse<null>>; deleteDocument: (docId: number) => Promise<IpcResponse<null>>; chooseFile: () => Promise<IpcResponse<unknown>> }
      tasks: { list: (f?: unknown) => Promise<IpcResponse<unknown>>; getById: (id: number) => Promise<IpcResponse<unknown>>; create: (d: unknown) => Promise<IpcResponse<{ id: number }>>; update: (id: number, d: unknown) => Promise<IpcResponse<null>>; delete: (id: number) => Promise<IpcResponse<null>>; getForCalendar: (from: string, to: string) => Promise<IpcResponse<unknown[]>>; setAssignees: (taskId: number, userIds: number[]) => Promise<IpcResponse<null>>; createDelivery: (d: unknown) => Promise<IpcResponse<{ id: number }>>; getSummary: () => Promise<IpcResponse<unknown>> }
      notifications: { list: (limit?: number) => Promise<IpcResponse<unknown[]>>; getUnreadCount: () => Promise<IpcResponse<number>>; markRead: (id: number) => Promise<IpcResponse<null>>; markAllRead: () => Promise<IpcResponse<null>> }
    }
  }
}
